data "azurerm_client_config" "current" {}


resource "azuread_group" "groups" {
  for_each           = var.group_assignments
  display_name       = each.key
  description        = "Automatically generated by terraform: %{for role_desc in local.group_desc[each.key]~}${role_desc}%{endfor~}"
  security_enabled   = true
  assignable_to_role = contains(var.pim_enabled_groups, each.key)
}

resource "azurerm_role_assignment" "role_assignments" {
  for_each             = local.group_role_assignments
  scope                = each.value.scope
  role_definition_name = each.value.role_definition_name
  role_definition_id   = each.value.role_definition_id
  principal_id         = azuread_group.groups[each.value.principal].object_id
}
